

  spring:
    datasource:
      url: 'jdbc:postgresql://localhost:5432/airline'
      username: postgres
      password: 123
      driver-class-name: 'org.postgresql.Driver'
    jpa:
     hibernate:
      ddl-auto: update
     show-sql: true
     properties:
      hibernate:
        format_sql: true

    mail:
      host: smtp.mailtrap.io
      port: 587
      username: 257f5dcceaeb82
      password: cf6e4c8fb64c6f
      properties:
        mail:
          smtp:
            auth: true
            starttls:
              enable: true
  openapi: 3.0.0
  info:
    title: Your API
    version: 1.0.0
  paths:
    /admin/resource:
      get:
        tags:
          - ADMIN
        summary: "Get admin resource"
        responses:
          '200':
            description: "Successful response"

    /customer/resource:
      get:
        tags:
          - CUSTOMER
        summary: "Get customer resource"
        responses:
          '200':
            description: "Successful response"

    /agent/resource:
      get:
        tags:
          - AGENT
        summary: "Get agent resource"
        responses:
          '200':
            description: "Successful response"